### ISSUE TITLE
Warning Fix: resolve warning that originated from 'react-modal' upgrade

### ISSUE THREAD

**Issue by tnewell5** [stride-nyc/remote_retro#328] opened 2017-12-01 20:01 UTC
As a contributor,
I want the warning that originated from 'react-modal' upgrade resolved,
So that the developer console is clear of warnings.

__By Way Of Explanation:__ 
After upgrading of 'react-modal', the following warning appeared in the console:
![image](https://user-images.githubusercontent.com/8727588/33500819-45a95184-d6a8-11e7-9736-ef6f262414f3.png)

__Acceptance Criteria:__

- [ ] The warning displayed in this story is resolved and no longer appears in the console.

__Helpful Links:__

https://github.com/reactjs/react-modal/issues/133

**Comment by vanderhoop** [comment] 2018-01-10 02:17
closing due to an inability to reproduce

**Closed by vanderhoop** 2018-01-10 02:17 UTC
Labels: chore
