### ISSUE TITLE
Share retros + authentication

### ISSUE THREAD

**Issue by pulsedemon** [stride-nyc/remote_retro#107] opened 2017-04-21 19:56 UTC
- User shares a retro
- Authentication checks that this user had the retro shared with them
- Users can only view retros for which they have permission

**Comment by vanderhoop** [comment] 2017-06-17 16:22
closing, as the intended behavior is for any user with access to the retro link (which has a snowflake id) to be able to access the retro, not unlike secret Gists

**Closed by vanderhoop** 2017-06-17 16:22 UTC
