### ISSUE TITLE
Remove an accidental vote

### ISSUE THREAD

**Issue by ddipanfilo** [stride-nyc/remote_retro#281] opened 2017-09-19 23:07 UTC
As a participant, I want to be able to remove my votes
So that if I accidentally voted on something or changed my mind, I can remove that vote.

**Comment by vanderhoop** [comment] 2017-11-20 16:33
hey @ddipanfilo, closing this as a duplicate of #275 (Feature Request: Detract a Vote)

**Closed by vanderhoop** 2017-11-20 16:33 UTC
