### ISSUE TITLE
Feature request: Add ability to undo a Vote

### ISSUE THREAD

**Issue by jennysoup** [stride-nyc/remote_retro#512] opened 2019-01-25 13:57 UTC
As a user,
I want the ability to undo a Vote
So that I can use my 3 votes properly.

__By Way Of Explanation:__ If during the voting period, we change our minds on a vote, it's difficult to undo the vote and then allocate the vote to another idea. 

__Acceptance Criteria:__

- [ ] When I click on a part of the vote button, if I have voted for that item, I am able to undo the vote.

**Comment by vanderhoop** [comment] 2019-02-08 00:07
@jennysoup! Hello! Thanks for creating this. It's been requested before, so going to close this as a duplicate of #275. We'll likely get to this after we've implemented the grouping/deduping stage, as that will likely change the voting interface

**Closed by vanderhoop** 2019-02-08 00:07 UTC

**Comment by vanderhoop** [comment] 2019-02-21 21:07
hey @jennysoup, our new voting interface is now live 😄 🎉

**Comment by jennysoup** [comment] 2019-02-22 14:38
@vanderhoop this is awesome, thank you!
