### ISSUE TITLE
Bug: Facilitator unable to add/edit group labels

### ISSUE THREAD

**Issue by jaryncolbert** [stride-nyc/remote_retro#563] opened 2020-03-20 20:13 UTC
As a facilitator
I want to add labels to the groups generated during the retro's Grouping phase
So that the final retro view is organized.

__By Way Of Explanation:__ (optional)
I was the facilitator on a retro this morning, and though we've used Remote Retro before, it was our first time using the new Grouping feature.

Initially, we did not realize that leaving the groups unlabeled would result in a final view where each ungrouped idea was given its own box; we preferred having the ideas grouped in their original Happy/Sad/Confused columns.

I restarted another retro to learn in which phase we should have labeled the groups, and when I tried editing the "Optional Group Label" headers during the "Labeling & Voting" phase, the inputs appeared to be disabled for editing. 

__Acceptance Criteria:__
- [x] Even if group labels are optional, clicking the label should allow them to be edited by the facilitator

**Comment by vanderhoop** [comment] 2020-03-22 00:41
@jaryncolbert, can't thank you enough for surfacing this. The issue was caused by a hastily added negative `z-index`, and our end to end tests didn't catch it due to the way they interact with the form inputs. Fixed in dcb5812. Thanks again!

**Closed by vanderhoop** 2020-03-22 00:41 UTC
